#!/bin/bash
# Markdug trigger installer (skhd)
#
# Sets up the global ⌥Space hotkey that launches Markdug, with no dependency
# on Keyboard Maestro. Run once per Mac, after ./build.sh has installed the app:
#   chmod +x install-trigger.sh && ./install-trigger.sh
#
# What it does:
#   1. Installs skhd (a tiny, free, open-source hotkey daemon) via Homebrew
#   2. Installs this repo's skhdrc to ~/.skhdrc, pointing at this repo's km-macro.sh
#   3. Starts skhd as a LaunchAgent so it auto-runs at every login
#   4. Tells you how to grant the one-time Accessibility permission

set -e

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
MACRO_PATH="$PROJECT_DIR/km-macro.sh"

echo "🔨 Installing Markdug trigger (skhd)..."

# ── Homebrew check ───────────────────────────────────────────────────────────
if ! command -v brew &> /dev/null; then
    echo "❌ Homebrew not found. Install it from https://brew.sh then re-run."
    exit 1
fi

# ── Install skhd ─────────────────────────────────────────────────────────────
if command -v skhd &> /dev/null; then
    echo "✅ skhd already installed ($(skhd --version))"
else
    echo "📦 Installing skhd..."
    brew install koekeishiya/formulae/skhd
fi

# ── Make sure the macro script is executable ─────────────────────────────────
chmod +x "$MACRO_PATH"

# ── Write ~/.skhdrc, pointing at THIS repo's km-macro.sh ─────────────────────
# (rewrites the path so it works regardless of where the repo was cloned)
echo "📝 Writing ~/.skhdrc..."
cat > "$HOME/.skhdrc" << EOF
# skhd config for Markdug — generated by install-trigger.sh
# Option+Space renders the .md file selected in Finder (toggles closed if open).
alt - space : $MACRO_PATH
EOF

# ── Start / restart the login service ────────────────────────────────────────
echo "🚀 Starting skhd service..."
skhd --restart-service 2>/dev/null || skhd --start-service

echo ""
echo "✅ Trigger installed!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ONE MANUAL STEP — grant Accessibility permission:"
echo ""
echo "  System Settings → Privacy & Security → Accessibility → +"
echo "  Add:  $(command -v skhd)"
echo "  Toggle it ON, then run:  skhd --restart-service"
echo ""
echo "  Then select a .md file in Finder and press ⌥Space to test."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
